/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RCDAQ_RPC_H_RPCGEN
#define _RCDAQ_RPC_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define STATUSFORMAT_SHORT 0
#define STATUSFORMAT_NORMAL 1
#define STATUSFORMAT_LONG 2
#define STATUSFORMAT_VLONG 3

struct shortResult {
	char *str;
	int content;
	int what;
	int status;
};
typedef struct shortResult shortResult;

struct actionblock {
	int action;
	int ipar[16];
	float value;
	int spare;
	char *spar;
	char *spar2;
};
typedef struct actionblock actionblock;
#define NSTRINGPAR 14

struct deviceblock {
	int npar;
	char *argv0;
	char *argv1;
	char *argv2;
	char *argv3;
	char *argv4;
	char *argv5;
	char *argv6;
	char *argv7;
	char *argv8;
	char *argv9;
	char *argv10;
	char *argv11;
	char *argv12;
	char *argv13;
};
typedef struct deviceblock deviceblock;

#define RCDAQ 0x3feeeffc
#define RCDAQ_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define r_action 1
extern  shortResult * r_action_1(actionblock *, CLIENT *);
extern  shortResult * r_action_1_svc(actionblock *, struct svc_req *);
#define r_create_device 2
extern  shortResult * r_create_device_1(deviceblock *, CLIENT *);
extern  shortResult * r_create_device_1_svc(deviceblock *, struct svc_req *);
#define r_shutdown 3
extern  shortResult * r_shutdown_1(void *, CLIENT *);
extern  shortResult * r_shutdown_1_svc(void *, struct svc_req *);
extern int rcdaq_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define r_action 1
extern  shortResult * r_action_1();
extern  shortResult * r_action_1_svc();
#define r_create_device 2
extern  shortResult * r_create_device_1();
extern  shortResult * r_create_device_1_svc();
#define r_shutdown 3
extern  shortResult * r_shutdown_1();
extern  shortResult * r_shutdown_1_svc();
extern int rcdaq_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_shortResult (XDR *, shortResult*);
extern  bool_t xdr_actionblock (XDR *, actionblock*);
extern  bool_t xdr_deviceblock (XDR *, deviceblock*);

#else /* K&R C */
extern bool_t xdr_shortResult ();
extern bool_t xdr_actionblock ();
extern bool_t xdr_deviceblock ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RCDAQ_RPC_H_RPCGEN */
