/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "rcdaq_rpc.h"

bool_t
xdr_shortResult (XDR *xdrs, shortResult *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->str, ~0))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->content))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->what))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->status))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_actionblock (XDR *xdrs, actionblock *objp)
{
	register int32_t *buf;

	int i;

	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, (1 + ( 16 )) * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->action))
				 return FALSE;
			 if (!xdr_vector (xdrs, (char *)objp->ipar, 16,
				sizeof (int), (xdrproc_t) xdr_int))
				 return FALSE;

		} else {
		IXDR_PUT_LONG(buf, objp->action);
		{
			register int *genp;

			for (i = 0, genp = objp->ipar;
				i < 16; ++i) {
				IXDR_PUT_LONG(buf, *genp++);
			}
		}
		}
		 if (!xdr_float (xdrs, &objp->value))
			 return FALSE;
		 if (!xdr_int (xdrs, &objp->spare))
			 return FALSE;
		 if (!xdr_string (xdrs, &objp->spar, ~0))
			 return FALSE;
		 if (!xdr_string (xdrs, &objp->spar2, ~0))
			 return FALSE;
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, (1 + ( 16 )) * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->action))
				 return FALSE;
			 if (!xdr_vector (xdrs, (char *)objp->ipar, 16,
				sizeof (int), (xdrproc_t) xdr_int))
				 return FALSE;

		} else {
		objp->action = IXDR_GET_LONG(buf);
		{
			register int *genp;

			for (i = 0, genp = objp->ipar;
				i < 16; ++i) {
				*genp++ = IXDR_GET_LONG(buf);
			}
		}
		}
		 if (!xdr_float (xdrs, &objp->value))
			 return FALSE;
		 if (!xdr_int (xdrs, &objp->spare))
			 return FALSE;
		 if (!xdr_string (xdrs, &objp->spar, ~0))
			 return FALSE;
		 if (!xdr_string (xdrs, &objp->spar2, ~0))
			 return FALSE;
	 return TRUE;
	}

	 if (!xdr_int (xdrs, &objp->action))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->ipar, 16,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->value))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->spare))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->spar, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->spar2, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_deviceblock (XDR *xdrs, deviceblock *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->npar))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->argv0, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->argv1, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->argv2, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->argv3, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->argv4, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->argv5, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->argv6, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->argv7, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->argv8, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->argv9, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->argv10, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->argv11, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->argv12, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->argv13, ~0))
		 return FALSE;
	return TRUE;
}
