/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "rcdaq_rpc.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

shortResult *
r_action_1(actionblock *argp, CLIENT *clnt)
{
	static shortResult clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, r_action,
		(xdrproc_t) xdr_actionblock, (caddr_t) argp,
		(xdrproc_t) xdr_shortResult, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

shortResult *
r_create_device_1(deviceblock *argp, CLIENT *clnt)
{
	static shortResult clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, r_create_device,
		(xdrproc_t) xdr_deviceblock, (caddr_t) argp,
		(xdrproc_t) xdr_shortResult, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

shortResult *
r_shutdown_1(void *argp, CLIENT *clnt)
{
	static shortResult clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, r_shutdown,
		(xdrproc_t) xdr_void, (caddr_t) argp,
		(xdrproc_t) xdr_shortResult, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
